# Generated by Django 3.2.6 on 2021-08-17 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confeiteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=15)),
                ('classificacao', models.CharField(choices=[('A', '⭐⭐⭐⭐⭐'), ('B', '⭐⭐⭐⭐'), ('C', '⭐⭐⭐'), ('D', '⭐⭐'), ('E', '⭐')], default='A', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('data_fabricacao', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 29, 21, 151873, tzinfo=utc))),
                ('data_validade', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 29, 21, 151873, tzinfo=utc))),
                ('mostrar', models.BooleanField(default=True)),
                ('confeiteiro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.confeiteiro')),
            ],
        ),
    ]
