# Generated by Django 3.2.6 on 2021-08-17 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='data_fabricacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 48, 21, 25889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='data_validade',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 48, 21, 25889, tzinfo=utc)),
        ),
    ]
