# Generated by Django 3.2.6 on 2021-08-17 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210817_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='data_fabricacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 48, 44, 256547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='data_validade',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 48, 44, 256547, tzinfo=utc)),
        ),
    ]
