# Generated by Django 3.2.6 on 2021-08-17 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210817_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='data_fabricacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 52, 2, 575209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='data_validade',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 12, 52, 2, 575209, tzinfo=utc)),
        ),
    ]
